AllCops:
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 11

Metrics/AbcSize:
  Max: 20

Style/RedundantFreeze:
  Enabled: false

Style/Documentation:
  Exclude:
    - chproxy.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - chproxy.rb

Layout/SpaceAroundOperators:
  Exclude:
    - chproxy.rb
