AllCops:
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 11
  Exclude:
    - lib/chproxy/init_command.rb

Metrics/AbcSize:
  Max: 20

Lint/RescueWithoutErrorClass:
  Exclude:
    - 'spec/**/*.rb'

Style/RedundantFreeze:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/RescueModifier:
  Exclude:
    - 'spec/**/*.rb'

Style/SafeNavigation:
  Exclude:
    - lib/chproxy/executor.rb

Layout/SpaceAroundOperators:
  Exclude:
    - chproxy.rb

Layout/IndentHeredoc:
  Exclude:
    - spec/chproxy/init_command_spec.rb
